services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn attendance_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: attendance_system.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      # MongoDB Atlas variables
      - key: MONGODB_URI
        value: mongodb+srv://tharunkumar9113:Tharun9535@facerecognition.0arqyns.mongodb.net/?retryWrites=true&w=majority&appName=facerecognition
      - key: MONGODB_NAME
        value: attendance_db
      - key: MONGODB_USERNAME
        value: tharunkumar9113
      - key: MONGODB_PASSWORD
        value: Tharun9535
      - key: EMAIL_HOST_USER
        value: tharunkumar9113@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: kyfc uirt oikl fgcs

databases:
  - name: mydb
    plan: free 