# Generated by Django 3.2 on 2025-05-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'marked_by')},
        ),
    ]
